### ISSUE TITLE
Problems when running scannet test script

### ISSUE THREAD

**Issue by kyrie970911** [zju3dv/NeuralRecon#12]
Many thanks for your great work!

I'm trying to run it on the scannet dataset and already prepared the data following the recommended structure. After I run `python main.py` with config/test.yaml (scannet path modified), it turns out error with:

`
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    test()
  File "main.py", line 266, in test
    save_mesh_scene(outputs, sample, epoch_idx)
TypeError: __call__() missing 1 required positional argument: 'frag_idx'
`

It seems a missing argument for save_mesh_scene. I checked the utils.py and removed that argument in SaveScene's call method since it's not used, but then the problem changed into the "last_frag" not defined in Line 306 in File "utils.py". Even removing that condition, I still can't get the visualization and the problem is the keyerror: 'scene_tsdf' in outputs.

Before this I have successfully run the demo with the given demo data.

Thanks for your help!

**Comment by JiamingSuen** [comment]
We recently updated a few interfaces in `SaveScene` to smooth out some difficulties running the demo, and function calls in `main.py` are not updated accordingly. We will fix this issue in a few hours. I'll come back to you soon.

**Comment by kyrie970911** [comment]
I see. That would be really appreciated!

**Comment by JiamingSuen** [comment]
This issue should be fixed in #13. Feel free to reopen this issue if you find any problem.
