### ISSUE TITLE
scannet.py FileNotFoundError

### ISSUE THREAD

**Issue by guardian1213812138** [zju3dv/NeuralRecon#132]
When I run the main.py, the error message 'FileNotFoundError: [Errno 2] No such file or directory:'home/***/***/***/***/data''appears, which is located in scannet. py. But the corresponding file can be found in the corresponding path. The detailed error information is as follows.

creating log file ./checkpoints/20230520_160409_train.log
Traceback (most recent call last):
  File "/home/a123/ShiShi/NeuralRecon/NeuralRecon-master/venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-71360b6de68b>", line 1, in <module>
    runfile('/home/a123/ShiShi/NeuralRecon/NeuralRecon-master/main.py', args=['--cfg', './config/train.yaml'], wdir='/home/a123/ShiShi/NeuralRecon/NeuralRecon-master')
  File "/home/a123/pycharm-2021.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/a123/pycharm-2021.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/a123/ShiShi/NeuralRecon/NeuralRecon-master/main.py", line 117, in <module>
    train_dataset = MVSDataset(cfg.TRAIN.PATH, "train", transforms, cfg.TRAIN.N_VIEWS, len(cfg.MODEL.THRESHOLDS) - 1)
  File "/home/a123/ShiShi/NeuralRecon/NeuralRecon-master/datasets/scannet.py", line 19, in __init__
    self.metas = self.build_list()
  File "/home/a123/ShiShi/NeuralRecon/NeuralRecon-master/datasets/scannet.py", line 32, in build_list
    with open(os.path.join('home/a123/ShiShi/NeuralRecon/NeuralRecon-master/data', self.tsdf_file, 'fragments_{}.pkl'.format(self.mode)), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'home/a123/ShiShi/NeuralRecon/NeuralRecon-master/data/all_tsdf_9/fragments_train.pkl'

I would greatly appreciate it if you could solve this problem.

**Comment by guardian1213812138** [comment]
scannet.py line 32
with open(os.path.join('home/a123/ShiShi/NeuralRecon/NeuralRecon-master/data', self.tsdf_file, 'fragments_{}.pkl'.format(self.mode)), 'rb') as f:

**Comment by Jamesgender** [comment]
If you finished the process of generating GT, the fragments_train.pkl will be there.
