### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Nekomiya-fubuki** [zju3dv/NeuralRecon#18]
Excuse me,can I ask a question?I follow the DEMO step by step,but I come cross a erro.Can you tell me how to solve it?

2021-06-05 15:28:46.856 | INFO     | __main__:<module>:35 - Found SyncedPoses.txt, skipping data pre-processing...
2021-06-05 15:28:46.856 | INFO     | __main__:<module>:37 - Running NeuralRecon...
2021-06-05 15:28:46.874 | INFO     | __main__:<module>:50 - Initializing the model on GPU...
2021-06-05 15:28:50.821 | INFO     | __main__:<module>:58 - Resuming from ./checkpoints/model_000047.ckpt
2021-06-05 15:28:51.211 | INFO     | __main__:<module>:64 - Start inference..
  0%|                                                   | 0/110 [00:00<?, ?it/s]/home/u/Documents/NeuralRecon-master/ops/back_project.py:29: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629427478/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  batch_ind = torch.nonzero(coords[:, 0] == batch).squeeze(1)
  0%|                                                   | 0/110 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 76, in <module>
    outputs, loss_dict = model(sample, save_scene)
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u/Documents/NeuralRecon-master/models/neuralrecon.py", line 82, in forward
    outputs, loss_dict = self.neucon_net(features, inputs, outputs)
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u/Documents/NeuralRecon-master/models/neucon_network.py", line 157, in forward
    feat = self.sp_convs[i](point_feat)
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/u/Documents/NeuralRecon-master/models/modules.py", line 147, in forward
    x0 = initial_voxelize(z, self.pres, self.vres)
  File "/home/u/Documents/NeuralRecon-master/ops/torchsparse_utils.py", line 19, in initial_voxelize
    pc_hash = spf.sphash(torch.floor(new_float_coord).int())
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 39, in sphash
    return HashGPU.apply(idx)
  File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 11, in forward
    return torchsparse_backend.hash_forward(idx.contiguous())
AttributeError: module 'torchsparse_backend' has no attribute 'hash_forward'

**Comment by JiamingSuen** [comment]
This should be an environment configuration problem. Please make sure that `torchsparse` is correctly installed and compilation by the end of the installation is succeeded.

**Comment by JiamingSuen** [comment]
Closed due to inactivity. Feel free to reopen this issue if you would like to continue the conversation. @Nekomiya-fubuki

**Comment by Nekomiya-fubuki** [comment]
I'm sorry to have taken so long to get back to you.Recently,I've installed the system and configurate environment again,but this error is still display.I'm sure torchsparse is correctly installed and compilation by the end of the installation is succeeded.
