### ISSUE TITLE
Train script not working. ['vol_origin_partial'] information missing in generate_gt.py

### ISSUE THREAD

**Issue by chinmay1148** [zju3dv/NeuralRecon#90]
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    train()
  File "main.py", line 214, in train
    loss, scalar_outputs = train_sample(sample) ### Training is done here
  File "main.py", line 290, in train_sample
    outputs, loss_dict = model(sample)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfs-volume/NeuralRecon-rgbd/models/neuralrecon.py", line 119, in forward
    outputs, loss_dict = self.neucon_net(features, inputs, outputs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfs-volume/NeuralRecon-rgbd/models/neucon_network.py", line 130, in forward
    volume, count = back_project(up_coords, inputs['vol_origin_partial'], self.cfg.VOXEL_SIZE, feats,
KeyError: 'vol_origin_partial'

The key 'vol_origin_partial' is not present in generate_gt.py while generating the fragment.pkl  file.
This information is needed in back_proj function.

**Comment by chinmay1148** [comment]
this issue is resolved. Caused due to commenting out the transforms function in dataset/scannet.py
